# Generated by Django 3.2.3 on 2021-06-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('gmail', models.EmailField(max_length=59)),
                ('description', models.TextField()),
                ('linkedinlink', models.CharField(max_length=80)),
                ('githublink', models.CharField(max_length=80)),
                ('twitterlink', models.CharField(max_length=80)),
                ('facebooklink', models.CharField(max_length=80)),
                ('fiverlink', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituate_name', models.CharField(max_length=50)),
                ('degree_name', models.CharField(max_length=50)),
                ('course_name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.CharField(default='Present', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('organization_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.CharField(default='Present', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
    ]
