# Generated by Django 3.2.3 on 2021-06-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='cv/')),
            ],
        ),
    ]
