# Generated by Django 3.2.3 on 2021-07-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0004_my_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cv_upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
