# Generated by Django 3.2.3 on 2021-07-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycv', '0005_about_cv_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='description',
        ),
        migrations.AddField(
            model_name='interest',
            name='interst',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
